services:
  otrta-ui:
    container_name: otrta-ui
    build:
      context: ui
    environment:
      - NEXT_PUBLIC_API_URL=http://otrta-rust:3333
    networks:
      - otrta-network
    ports:
      - 3332:3000
    restart: unless-stopped

  otrta-rust:
    container_name: otrta-rust
    build:
      context: otrta
      dockerfile: Dockerfile.client
    environment:
      - RUST_LOG=debug
      - APP_ENVIRONMENT=production
    env_file:
      - .env
    ports:
      - 3333:3333
    networks:
      - otrta-network
    volumes:
      - backend_cache:/code/target
    # extra_hosts:
    #   - 'host.docker.internal:host-gateway'
    depends_on:
      - otrta-db
    restart: unless-stopped

  otrta-db:
    container_name: otrta-db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=otrta
    networks:
      - otrta-network
    ports:
      - 5436:5432
    volumes:
      - psqldata:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  otrta-network:
    external: true

volumes:
  backend_cache: {}
  psqldata: {}
